# Generated by Django 4.0.2 on 2022-04-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metazoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
